"""add persona and few_shot_examples to training_jobs

Revision ID: 06ae34d9abe5
Revises: 35252858424d
Create Date: 2026-06-15 09:04:41.118568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ae34d9abe5'
down_revision: Union[str, None] = '35252858424d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_jobs', sa.Column('persona', sa.Text(), nullable=True))
    op.add_column('training_jobs', sa.Column('few_shot_examples', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_jobs', 'few_shot_examples')
    op.drop_column('training_jobs', 'persona')
    # ### end Alembic commands ###
