"""add projects and inference_temperature

Revision ID: 504bfdc043c7
Revises: 22391df9b610
Create Date: 2026-06-23 07:06:36.973442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '504bfdc043c7'
down_revision: Union[str, None] = '22391df9b610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # [FIX] projects/project_datasets must exist before the FK on training_jobs
    # below can reference them. The original autogenerate run split table creation
    # into a later migration (8ab63d886f89) while putting this FK here — that
    # ordering fails on a genuinely fresh database with
    # "relation \"projects\" does not exist". Moved table creation up to this
    # migration; 8ab63d886f89 no longer creates them (see that file).
    op.create_table('projects',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('use_case', sa.String(), nullable=True),
        sa.Column('persona', sa.Text(), nullable=False),
        sa.Column('few_shot_examples', sa.JSON(), nullable=True),
        sa.Column('base_model_name', sa.String(), nullable=False),
        sa.Column('hyperparameters', sa.JSON(), nullable=True),
        sa.Column('inference_temperature', sa.Float(), nullable=True),
        sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'TRAINING', 'COMPLETED', 'FAILED', name='jobstatus', create_type=False), nullable=True),
        sa.Column('progress', sa.Integer(), nullable=True),
        sa.Column('epoch', sa.Integer(), nullable=True),
        sa.Column('metrics', sa.JSON(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('project_datasets',
        sa.Column('project_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('dataset_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id']),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id']),
        sa.PrimaryKeyConstraint('project_id', 'dataset_id'),
    )

    op.add_column('model_artifacts', sa.Column('adapter_path', sa.String(), nullable=True)) # i have done this due to old test data had some null values
    # [FIX] Backfill adapter_path from the old s3_path column before dropping it.
    # The original migration dropped s3_path with no copy step, which would have
    # silently orphaned the file path on every existing ModelArtifact row (that
    # column never actually held an S3 path — see the original PDF's L1 finding —
    # so the rename is correct, but it still needs a data copy, not a straight drop).
    op.execute("UPDATE model_artifacts SET adapter_path = s3_path WHERE s3_path IS NOT NULL")
    op.drop_column('model_artifacts', 's3_path')
    op.add_column('training_jobs', sa.Column('project_id', sa.UUID(), nullable=True))
    op.add_column('training_jobs', sa.Column('version', sa.Integer(), nullable=True))
    op.alter_column('training_jobs', 'dataset_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('training_jobs', 'base_model_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('training_jobs', 'hyperparameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.create_foreign_key(None, 'training_jobs', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE: op.drop_constraint(None, ...) below requires Alembic to look up the
    # FK's actual database-assigned name from a live connection — this only
    # works when downgrade() runs against a real, connected database, not via
    # `alembic downgrade ... --sql` (offline mode), which has no connection to
    # resolve the constraint name from. This is a pre-existing limitation of the
    # original autogenerated migration, not something introduced by the table-
    # ordering fix above. The upgrade() path (what actually matters for
    # deploying) is unaffected and has been verified via --sql end to end.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'training_jobs', type_='foreignkey')
    op.alter_column('training_jobs', 'hyperparameters',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('training_jobs', 'base_model_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('training_jobs', 'dataset_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('training_jobs', 'version')
    op.drop_column('training_jobs', 'project_id')
    op.add_column('model_artifacts', sa.Column('s3_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.execute("UPDATE model_artifacts SET s3_path = adapter_path WHERE adapter_path IS NOT NULL")
    op.drop_column('model_artifacts', 'adapter_path')

    op.drop_table('project_datasets')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
