"""add task_id to training_jobs

Revision ID: c28450717189
Revises: c4e8b2f6a1d3
Create Date: 2026-07-17 22:20:19.002849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28450717189'
down_revision: Union[str, None] = 'c4e8b2f6a1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('deployment_usage_project_id_fkey', 'deployment_usage', type_='foreignkey')
    op.create_foreign_key(None, 'deployment_usage', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('training_jobs', sa.Column('task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_jobs', 'task_id')
    op.drop_constraint(None, 'deployment_usage', type_='foreignkey')
    op.create_foreign_key('deployment_usage_project_id_fkey', 'deployment_usage', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
